from crewai import Agent, Crew, Task, Process, LLM
from crewai.project import CrewBase, agent, task, crew
from crewai_tools import SerperDevTool

# FileReadTool                 read and extract data from files
# FileWriterTool               write contents to files
# CodeInterpreterTool          execute python code generated by agent
# ScrapeWebsiteTool            read and extract content of a website
# SerperDevTool                retrieve search results from the internet
# DirectoryReadTool            list the contents of a directory
# FirecrawlSearchTool          search and convert the websites to markdown 
# BrowserbaseLoadTool          run, manage and monitor headless browsers
#t PDFSearchTool               RAG tool for searching in PDFs
# GithubSearchTool             RAG tool for searching in Github repo
# TXTSearchTool                RAG tool for searching in text filkes 
# NL2SQLTool                   convert natural language to SQL queries

# CrewBase : a decrator that allows modular Crew classes
# wrap everything inside a single class that dynamically loads agents and classes 


@CrewBase
class ResearchCrew:
    """A crew for conducting research, 
    summarizing-findings, fact-checking, 
    and content-writing"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    def __init__(self):
        self.search_tool = SerperDevTool() # defines a web search tool for relevant information 
        self.qwen_llm = LLM(
            model="ollama/qwen3.5:4b",
            base_url="http://localhost:11434"
        )

    # __init__ (The constructor)
    # runs automatically the moment you create a new instance of the crew
    # sets initial state of the object; usually where LLMs and Tools are ready for agents to use 

    # similarly, we define the Agent and Task decorators
    @agent
    def research_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['research_agent'],
            tools=[self.search_tool],
            llm=self.qwen_llm
        )

    @agent
    def summarization_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['summarization_agent'],
            llm=self.qwen_llm
        )

    @agent
    def fact_checker_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['fact_checker_agent'],
            tools=[self.search_tool],
            llm=self.qwen_llm
        )

    @agent
    def content_writer_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['content_writer_agent'],
            llm=self.qwen_llm
        )

    @task
    def research_task(self) -> Task:
        return Task(
            config=self.tasks_config['research_task'],
            agent=self.research_agent(),
            tools=[self.search_tool]
        )

    @task
    def summarization_task(self) -> Task:
        return Task(
            config=self.tasks_config['summarization_task'],
            agent=self.summarization_agent()
        )

    @task
    def fact_checking_task(self) -> Task:
        return Task(
            config=self.tasks_config['fact_checking_task'],
            tools=[self.search_tool],
            agent=self.fact_checker_agent()
        )

    @task
    def content_writing_task(self) -> Task:
        return Task(
            config=self.tasks_config['content_writing_task'],
            agent=self.content_writer_agent()
        )

    @crew # crew decorator defines the AI workflow 
    def crew(self) -> Crew:
        return Crew(
            agents=self.agents, # assign all dynamically created agents
            tasks=self.tasks, # assign all dynamically created tasks
            process=Process.sequential # run one task after the other; can be changed to hierarchical if needed
        )